package core.linlang.database.impl;

import api.linlang.file.database.DataService;

import java.util.Locale;
import java.util.regex.Pattern;

enum DatabaseDialect {
    H2 {
        @Override
        String booleanType() {
            return "BOOLEAN";
        }

        @Override
        String binaryType(int length) {
            return length > 0 ? "VARBINARY(" + length + ")" : "BLOB";
        }

        @Override
        String autoIncrement(String definition) {
            return definition + " GENERATED BY DEFAULT AS IDENTITY";
        }

        @Override
        String pagination(int limit, int offset) {
            StringBuilder sql = new StringBuilder();
            if (limit > 0) sql.append(" LIMIT ").append(limit);
            if (offset > 0) sql.append(" OFFSET ").append(offset);
            return sql.toString();
        }

        @Override
        String tableComment(String table, String comment) {
            return "COMMENT ON TABLE " + quote(table) + " IS " + stringLiteral(comment);
        }
    },
    MYSQL {
        @Override
        String booleanType() {
            return "TINYINT(1)";
        }

        @Override
        String binaryType(int length) {
            return length > 0 ? "VARBINARY(" + length + ")" : "LONGBLOB";
        }

        @Override
        String autoIncrement(String definition) {
            return definition + " AUTO_INCREMENT";
        }

        @Override
        String pagination(int limit, int offset) {
            if (limit > 0) {
                return " LIMIT " + limit + (offset > 0 ? " OFFSET " + offset : "");
            }
            if (offset > 0) {
                return " LIMIT 18446744073709551615 OFFSET " + offset;
            }
            return "";
        }

        @Override
        String tableComment(String table, String comment) {
            return "ALTER TABLE " + quote(table) + " COMMENT = " + stringLiteral(comment);
        }
    };

    private static final Pattern IDENTIFIER = Pattern.compile("[A-Za-z_][A-Za-z0-9_$]*");

    static DatabaseDialect from(DataService.DbType type) {
        return type == DataService.DbType.H2 ? H2 : MYSQL;
    }

    abstract String booleanType();

    abstract String binaryType(int length);

    abstract String autoIncrement(String definition);

    abstract String pagination(int limit, int offset);

    abstract String tableComment(String table, String comment);

    static String quote(String identifier) {
        if (identifier == null || !IDENTIFIER.matcher(identifier).matches()) {
            throw new IllegalArgumentException("Invalid database identifier: " + identifier);
        }
        return "`" + identifier + "`";
    }

    static String normalizeIdentifier(String identifier) {
        return identifier.toLowerCase(Locale.ROOT);
    }

    static String stringLiteral(String value) {
        return "'" + value.replace("'", "''") + "'";
    }
}
